# Generated by Django 4.2.5 on 2023-10-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.FloatField()),
                ('talle', models.CharField(blank=True, max_length=10, null=True, verbose_name='talle')),
            ],
        ),
    ]
